#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pipeline } from 'node:stream/promises';
import { fileURLToPath } from 'node:url';

const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(packageDir, '../..');
const sourceRoot = process.env.OPENWORK_ROOT?.trim()
  ? path.resolve(process.env.OPENWORK_ROOT)
  : repoRoot;
const runtimeDir = path.join(packageDir, 'runtime');
const packageRoot = path.join(runtimeDir, 'openwork');
const libDir = path.join(packageRoot, 'lib');
const nodeDir = path.join(packageRoot, 'node');
const binDir = path.join(packageRoot, 'bin');

const desktopVersion = JSON.parse(fs.readFileSync(path.join(packageDir, 'package.json'), 'utf8')).version;
const target = desktopTarget();
const skipBuild = process.env.OPENWORK_DESKTOP_SKIP_BUILD === '1';

if (!skipBuild) {
  const bun = process.platform === 'win32' ? 'bun.exe' : 'bun';
  console.log('Building OpenWork WebUI…');
  execFileSync(bun, ['run', 'webui:build'], { cwd: sourceRoot, stdio: 'inherit' });
  console.log('Building OpenWork server…');
  execFileSync(bun, ['run', 'server:build'], { cwd: sourceRoot, stdio: 'inherit' });
  console.log('Building session MCP server…');
  execFileSync(bun, ['run', 'server:build:subprocess'], { cwd: sourceRoot, stdio: 'inherit' });
}

fs.rmSync(packageRoot, { recursive: true, force: true });
fs.mkdirSync(packageRoot, { recursive: true });
fs.mkdirSync(libDir, { recursive: true });
fs.mkdirSync(nodeDir, { recursive: true });
fs.mkdirSync(binDir, { recursive: true });

// Stage WebUI
const webuiDist = path.join(sourceRoot, 'apps', 'webui', 'dist');
if (fs.existsSync(webuiDist)) {
  fs.cpSync(webuiDist, path.join(libDir, 'webui'), { recursive: true });
  console.log(`Staged WebUI into ${libDir}/webui`);
}

// Stage server
const serverDist = path.join(sourceRoot, 'packages', 'server');
if (fs.existsSync(serverDist)) {
  fs.cpSync(serverDist, path.join(libDir, 'server'), { recursive: true, filter: (src) => !src.includes('node_modules') });
  console.log(`Staged server into ${libDir}/server`);
}

// Stage session MCP server
const mcpDist = path.join(sourceRoot, 'packages', 'session-mcp-server', 'dist');
if (fs.existsSync(mcpDist)) {
  fs.cpSync(mcpDist, path.join(libDir, 'session-mcp-server'), { recursive: true });
  console.log(`Staged session MCP server into ${libDir}/session-mcp-server`);
}

// Stage resources (docs, themes, permissions, tool-icons, scripts)
const resourcesDir = path.join(libDir, 'resources');
const electronResources = path.join(sourceRoot, 'apps', 'electron', 'resources');
fs.mkdirSync(resourcesDir, { recursive: true });
for (const dir of ['docs', 'themes', 'permissions', 'tool-icons']) {
  const src = path.join(electronResources, dir);
  if (fs.existsSync(src)) {
    fs.cpSync(src, path.join(resourcesDir, dir), { recursive: true });
    console.log(`Staged ${dir}/ into ${resourcesDir}/${dir}`);
  }
}
const scriptsSrc = path.join(electronResources, 'scripts');
if (fs.existsSync(scriptsSrc)) {
  fs.cpSync(scriptsSrc, path.join(resourcesDir, 'scripts'), { recursive: true });
  console.log(`Staged doc tools into ${resourcesDir}/scripts`);
}
const binSrc = path.join(electronResources, 'bin');
if (fs.existsSync(binSrc)) {
  fs.cpSync(binSrc, path.join(resourcesDir, 'bin'), { recursive: true });
  console.log(`Staged binaries into ${resourcesDir}/bin`);
}

// Create cli-entry.js for the Tauri shell
const entryPath = path.join(libDir, 'cli-entry.js');
fs.writeFileSync(entryPath, [
  `#!/usr/bin/env node`,
  `// OpenWork desktop runtime entry`,
  `// Generated by prepare-runtime.js — ${new Date().toISOString()}`,
  ``,
  `// Forward OPENWORK_SERVER_TOKEN to CRAFT_SERVER_TOKEN`,
  `if (process.env.OPENWORK_SERVER_TOKEN && !process.env.CRAFT_SERVER_TOKEN) {`,
  `  process.env.CRAFT_SERVER_TOKEN = process.env.OPENWORK_SERVER_TOKEN`,
  `}`,
  `if (!process.env.CRAFT_RPC_PORT) process.env.CRAFT_RPC_PORT = '0'`,
  `if (!process.env.CRAFT_RPC_HOST) process.env.CRAFT_RPC_HOST = '127.0.0.1'`,
  ``,
  `// Parse CLI args`,
  `const argv = process.argv.slice(2)`,
  `for (let i = 0; i < argv.length; i++) {`,
  `  if (argv[i] === '--workspace' && i + 1 < argv.length) {`,
  `    process.env.CRAFT_WORKSPACE = argv[++i]`,
  `  } else if (argv[i] === '--port' && i + 1 < argv.length) {`,
  `    process.env.CRAFT_RPC_PORT = argv[++i]`,
  `  } else if (argv[i] === '--hostname' && i + 1 < argv.length) {`,
  `    process.env.CRAFT_RPC_HOST = argv[++i]`,
  `  }`,
  `}`,
  ``,
  `// Set WebUI directory`,
  `const runtimeDir = process.env.OPENWORK_DESKTOP_RUNTIME_DIR || __dirname + '/../../..'`,
  `const fs = require('fs'), path = require('path')`,
  `const webuiDir = path.join(runtimeDir, 'lib', 'webui')`,
  `if (fs.existsSync(webuiDir)) process.env.CRAFT_WEBUI_DIR = webuiDir`,
  ``,
  `// Load and start the server`,
  `require(path.join(__dirname, 'server', 'index.js'))`,
].join('\n'), 'utf8');
fs.chmodSync(entryPath, 0o755);

// Download and stage Node.js
const nodeVersion = fs.readFileSync(path.join(sourceRoot, '.nvmrc'), 'utf8').trim().replace(/^v/, '');
const nodeArchive = nodeArchiveName(target, nodeVersion);
const nodeArchiveUrl = `https://nodejs.org/dist/v${nodeVersion}/${nodeArchive}`;
const nodeArchivePath = path.join(nodeDir, nodeArchive);

console.log(`Downloading Node.js v${nodeVersion} for ${target}…`);
const response = await fetch(nodeArchiveUrl);
if (!response.ok) throw new Error(`Failed to download Node.js: HTTP ${response.status}`);
await pipeline(response.body, fs.createWriteStream(nodeArchivePath));

console.log('Verifying Node.js checksum…');
const sigs = await fetch(`https://nodejs.org/dist/v${nodeVersion}/SHASUMS256.txt`).then(r => r.text());
const expected = sigs.split('\n').find(l => l.includes(nodeArchive))?.split(/\s+/)[0];
if (!expected) throw new Error(`No checksum found for ${nodeArchive}`);
const actual = crypto.createHash('sha256').update(fs.readFileSync(nodeArchivePath)).digest('hex');
if (actual !== expected) throw new Error(`Node.js checksum mismatch. Expected: ${expected}, Actual: ${actual}`);

console.log('Extracting Node.js…');
if (target.startsWith('win')) {
  execFileSync('tar', ['-xf', nodeArchivePath, '-C', nodeDir, '--strip-components=1']);
} else {
  execFileSync('tar', ['-xzf', nodeArchivePath, '-C', nodeDir, '--strip-components=1']);
}
fs.rmSync(nodeArchivePath);

// Create launcher
if (target.startsWith('win')) {
  fs.writeFileSync(path.join(binDir, 'openwork.cmd'), `@echo off\r\n"${path.join(nodeDir, 'node.exe')}" "${entryPath}" %*`, 'utf8');
} else {
  const launcher = path.join(binDir, 'openwork');
  fs.writeFileSync(launcher, `#!/bin/sh\n"${path.join(nodeDir, 'bin', 'node')}" "${entryPath}" "$@"`, 'utf8');
  fs.chmodSync(launcher, 0o755);
}

// Manifest and checksums
const manifest = { version: desktopVersion, node: nodeVersion, target, generated: new Date().toISOString(), files: [] };
const checksums = {};
function walk(dir, base) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = path.relative(base, full);
    if (entry.isDirectory()) { walk(full, base) }
    else {
      const stat = fs.statSync(full);
      manifest.files.push({ path: rel, size: stat.size });
      checksums[rel] = crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex');
    }
  }
}
walk(packageRoot, packageRoot);
fs.writeFileSync(path.join(packageRoot, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
fs.writeFileSync(path.join(packageRoot, 'checksums.json'), JSON.stringify(checksums, null, 2), 'utf8');
console.log(`OpenWork runtime ${desktopVersion} prepared at ${packageRoot}`);

// ---- helpers ----
function desktopTarget() {
  const p = os.platform(), a = os.arch();
  if (p === 'darwin') return a === 'arm64' ? 'darwin-arm64' : 'darwin-x64';
  if (p === 'linux') return a === 'arm64' ? 'linux-arm64' : 'linux-x64';
  if (p === 'win32') return 'win-x64';
  throw new Error(`Unsupported platform: ${p} ${a}`);
}
function nodeArchiveName(target, version) {
  const prefix = `node-v${version}-`;
  switch (target) {
    case 'darwin-arm64': return `${prefix}darwin-arm64.tar.gz`;
    case 'darwin-x64': return `${prefix}darwin-x64.tar.gz`;
    case 'linux-arm64': return `${prefix}linux-arm64.tar.xz`;
    case 'linux-x64': return `${prefix}linux-x64.tar.xz`;
    case 'win-x64': return `${prefix}win-x64.zip`;
    default: throw new Error(`Unsupported target: ${target}`);
  }
}